### ISSUE TITLE
Retorno do Pagseguro

### ISSUE THREAD

**Issue by moirrer** [bruno-barros/PagSeguro-Codeigniter#1]
Olhei o fonte mas não consegui encontrar nada a respeito da resposta de pagamento do pagseguro.
Como faço para adicionar uma URL de retorno?

$config['reference'] = rand(999, 9999);
echo $this->pagseguro->get_button($config);

É algum outro parametro dentro do config?

**Comment by bruno-barros** [comment]
moirrer, você tem que configurar no PagSeguro o URL de retorno: http://seusite.com/exemplo/retorno_pagseguro

No controller `application/controllers/exemplo_ps.php` o método `retorno_pagseguro()` é um exemplo de como receber esse POST enviado pelo PagSeguro, mas toda lógica e tratamento do retorno é com você. ;-)
